//
//  Item+JsonGen.swift
//
//  Auto generated by swift-json-gen on Fri, 30 Oct 2015 12:42:16 GMT
//  See for details: https://github.com/tomlokhorst/swift-json-gen
//

import Foundation

extension Item {
  static func decodeJson(json: AnyObject) -> Item? {
    guard let dict = json as? [String : AnyObject] else {
      assertionFailure("json not a dictionary")
      return nil
    }

    guard let id_field: AnyObject = dict["id"] else {
      assertionFailure("field 'id' is missing")
      return nil
    }
    guard let id: String = String.decodeJson(id_field) else {
      assertionFailure("field 'id' is not a String")
      return nil
    }

    guard let name_field: AnyObject = dict["name"] else {
      assertionFailure("field 'name' is missing")
      return nil
    }
    guard let name: String = String.decodeJson(name_field) else {
      assertionFailure("field 'name' is not a String")
      return nil
    }

    guard let imageUrl_field: AnyObject = dict["imageUrl"] else {
      assertionFailure("field 'imageUrl' is missing")
      return nil
    }
    guard let imageUrl: String = String.decodeJson(imageUrl_field) else {
      assertionFailure("field 'imageUrl' is not a String")
      return nil
    }

    guard let price_field: AnyObject = dict["price"] else {
      assertionFailure("field 'price' is missing")
      return nil
    }
    guard let price: Double = Double.decodeJson(price_field) else {
      assertionFailure("field 'price' is not a Double")
      return nil
    }

    guard let discount_field: AnyObject = dict["discount"] else {
      assertionFailure("field 'discount' is missing")
      return nil
    }
    guard let discount: Double = Double.decodeJson(discount_field) else {
      assertionFailure("field 'discount' is not a Double")
      return nil
    }

    return Item(id: id, name: name, imageUrl: imageUrl, price: price, discount: discount)
  }

  func encodeJson() -> [String: AnyObject] {
    var dict: [String: AnyObject] = [:]

    dict["id"] = id.encodeJson()
    dict["name"] = name.encodeJson()
    dict["imageUrl"] = imageUrl.encodeJson()
    dict["price"] = price.encodeJson()
    dict["discount"] = discount.encodeJson()

    return dict
  }
}
