//
//  ItemList+JsonGen.swift
//
//  Auto generated by swift-json-gen on Fri, 30 Oct 2015 12:44:19 GMT
//  See for details: https://github.com/tomlokhorst/swift-json-gen
//

import Foundation

extension ItemList {
  static func decodeJson(json: AnyObject) -> ItemList? {
    guard let dict = json as? [String : AnyObject] else {
      assertionFailure("json not a dictionary")
      return nil
    }

    guard let items_field: AnyObject = dict["items"] else {
      assertionFailure("field 'items' is missing")
      return nil
    }
    guard let items: [Item] = Array.decodeJson({ Item.decodeJson($0) }, items_field) else {
      assertionFailure("field 'items' is not a [Item]")
      return nil
    }

    return ItemList(items: items)
  }

  func encodeJson() -> [String: AnyObject] {
    var dict: [String: AnyObject] = [:]

    dict["items"] = items.encodeJson({ $0.encodeJson() })

    return dict
  }
}
